#!/usr/bin/env bash

set -o nounset
set -o errexit

readonly dirs=(
    'etc/udev/rules.d'
)

cd "$(dirname ""${BASH_SOURCE[0]}"")"

for dir in "${dirs[@]}"; do
    mkdir -p "/$dir"
    for file in "$(ls -I '*~' -I '#*#' ""$dir"")"; do
        cp -v "$dir/$file" "/$dir/"
    done
done

udevadm control --reload
