#!/usr/bin/env bash

set -o nounset
set -o errexit

readonly packages=(
    base-devel
    dkms
    linux-headers
    broadcom-wl-dkms
    nvidia-340xx
)

pacman -S --needed "${packages[@]}"

readonly dirs=(
    'etc/modprobe.d'
    'etc/systemd/system/dhcpcd@wlp2s0.service.d'
    'etc/udev/rules.d'
    'etc/X11/xorg.conf.d'
    'usr/lib/systemd/system'
)

readonly services=(
    'disable-bluetooth.service'
    'disable-ir.service'
)

cd "$(dirname ""${BASH_SOURCE[0]}"")"

for dir in "${dirs[@]}"; do
    mkdir -p "/$dir"
    for file in $(ls -I '*~' -I '#*#' "$dir"); do
        cp -v "$dir/$file" "/$dir/"
    done
done

systemctl daemon-reload

for action in start enable; do
    for service in "${services[@]}"; do
        systemctl $action $service
    done
done

mkinitcpio -p linux
