#!/usr/bin/env bash

set -o nounset
set -o errexit

readonly dirs=(
    'usr/share/X11/xkb/symbols'
)

cd "$(dirname ""${BASH_SOURCE[0]}"")"

for dir in "${dirs[@]}"; do
    mkdir -p "/$dir"
    for file in $(ls -I '*~' -I '#*#' "$dir"); do
        cp -v "$dir/$file" "/$dir/"
    done
done

systemctl enable tlp
systemctl start tlp
