#!/usr/bin/env bash

set -o nounset
set -o errexit

readonly packages=(

  i3-wm
  i3lock
  i3status
  xorg-server
  xorg-xinit
  xorg-xev
  xss-lock
  rofi
  feh

  firefox

  tmux
  xterm
  rxvt-unicode
  xsel
  zsh
  zsh-completions

  git

  vim
  emacs

  pulseaudio
  pavucontrol

  ttf-dejavu
  ttf-liberation
  ttf-ubuntu-font-family
  otf-font-awesome
  noto-fonts
  noto-fonts-cjk
  noto-fonts-emoji
  adobe-source-sans-pro-fonts
  adobe-source-serif-pro-fonts

  jdk8-openjdk
  openjdk8-src

  argyllcms
  tlp
  powertop
  x86_energy_perf_policy
  ethtool
  smartmontools

  compton
  numlockx

  ibus
  ibus-libpinyin

  wpa_supplicant

  openssh
  keepassxc
)

pacman -S --needed "${packages[@]}"

ln -vsfn ../conf.avail/30-ttf-liberation-sans.conf  /etc/fonts/conf.d/
ln -vsfn ../conf.avail/30-ttf-liberation-serif.conf /etc/fonts/conf.d/
ln -vsfn ../conf.avail/30-ttf-liberation-mono.conf  /etc/fonts/conf.d/

readonly dirs=(
    'usr/share/X11/xkb/symbols'
)

cd "$(dirname ""${BASH_SOURCE[0]}"")"

for dir in "${dirs[@]}"; do
    mkdir -p "/$dir"
    for file in $(ls -I '*~' -I '#*#' "$dir"); do
        cp -v "$dir/$file" "/$dir/"
    done
done

# Arch
if [[ -d '/usr/share/kbd/keymaps/i386/qwerty/' ]]; then
    cp -v 'kbd/custom.map' '/usr/share/kbd/keymaps/i386/qwerty/'
fi

# Fedora
if [[ -d '/lib/kbd/keymaps/legacy/i386/qwerty/' ]]; then
    cp -v 'kbd/custom.map' '/lib/kbd/keymaps/legacy/i386/qwerty/'
fi

systemctl enable tlp
systemctl start tlp
localectl set-keymap custom

